#!/usr/bin/env python3
"""Indexer: scan markdown notes and write viewer/graph-data.js.

Usage: python3 build.py [notes_dir]    (default: ./notes next to this file)

Output: const GRAPH = {nodes: [...], links: [...]};
Every node's numeric `id` equals its index in GRAPH.nodes — the viewer and
the /chat endpoint both rely on that.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
DEFAULT_NOTES_DIR = os.path.join(ROOT, "notes")
OUTPUT = os.path.join(ROOT, "viewer", "graph-data.js")
EXCERPT_CHARS = 700

WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]")


def normalize(title):
    return re.sub(r"\s+", " ", title).strip().lower()


def clean_text(text):
    """Markdown -> readable plain-ish text for excerpts and scoring."""
    text = WIKILINK_RE.sub(lambda m: m.group(1), text)
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)
    lines = []
    for line in text.splitlines():
        if re.fullmatch(r"\s*\|?[\s:\-|]+\|?\s*", line) and "-" in line:
            continue  # table separator row
        line = re.sub(r"^#{1,6}\s*", "", line)
        line = line.replace("**", "").replace("__", "").replace("`", "")
        if line.strip().startswith("|"):
            line = " · ".join(c.strip() for c in line.strip().strip("|").split("|"))
        lines.append(line.rstrip())
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()


def make_excerpt(text, title, limit=EXCERPT_CHARS):
    # Drop a leading heading that just repeats the title.
    first, _, rest = text.partition("\n")
    if normalize(first) == normalize(title):
        text = rest.strip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    space = max(cut.rfind(" "), cut.rfind("\n"))
    if space > limit * 0.8:
        cut = cut[:space]
    return cut.rstrip(" ,.;:-·") + "…"


def load_notes(notes_dir=DEFAULT_NOTES_DIR):
    """Return notes in a stable order; list index == node id."""
    notes = []
    for dirpath, dirnames, filenames in os.walk(notes_dir):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for name in filenames:
            if not name.lower().endswith(".md"):
                continue
            path = os.path.join(dirpath, name)
            with open(path, encoding="utf-8", errors="replace") as f:
                raw = f.read()
            rel_dir = os.path.relpath(dirpath, notes_dir)
            group = "notes" if rel_dir == "." else os.path.basename(rel_dir)
            label = os.path.splitext(name)[0]
            notes.append({
                "label": label,
                "group": group,
                "path": os.path.relpath(path, notes_dir),
                "raw": raw,
                "text": clean_text(raw),
                "wikilinks": {normalize(w) for w in WIKILINK_RE.findall(raw)},
            })
    notes.sort(key=lambda n: (n["group"].lower(), n["label"].lower()))
    for i, n in enumerate(notes):
        n["id"] = i
    return notes


def build_links(notes):
    title_patterns = [
        re.compile(r"(?<![\w])" + re.escape(normalize(n["label"])) + r"(?![\w])")
        for n in notes
    ]
    lowered = [normalize(n["text"]) for n in notes]
    pairs = {}
    for a in notes:
        for b in notes:
            if a["id"] == b["id"]:
                continue
            key = (min(a["id"], b["id"]), max(a["id"], b["id"]))
            # a mentions b's title (plain text or as a [[wikilink]])
            if (normalize(b["label"]) in a["wikilinks"]
                    or title_patterns[b["id"]].search(lowered[a["id"]])):
                pairs.setdefault(key, set()).add("mention")
            # both link to the same [[target]] (that isn't either of them)
            shared = (a["wikilinks"] & b["wikilinks"]) - {normalize(a["label"]), normalize(b["label"])}
            if shared:
                pairs.setdefault(key, set()).add("shared")
    return [
        {"source": s, "target": t, "kind": "+".join(sorted(kinds))}
        for (s, t), kinds in sorted(pairs.items())
    ]


def build(notes_dir=DEFAULT_NOTES_DIR, output=OUTPUT, quiet=False):
    notes = load_notes(notes_dir)
    links = build_links(notes)
    degree = [0] * len(notes)
    for l in links:
        degree[l["source"]] += 1
        degree[l["target"]] += 1
    nodes = [{
        "id": n["id"],
        "label": n["label"],
        "group": n["group"],
        "path": n["path"],
        "excerpt": make_excerpt(n["text"], n["label"]),
        "degree": degree[n["id"]],
    } for n in notes]
    assert all(node["id"] == i for i, node in enumerate(nodes))

    os.makedirs(os.path.dirname(output), exist_ok=True)
    data = json.dumps({"nodes": nodes, "links": links}, indent=1, ensure_ascii=False)
    with open(output, "w", encoding="utf-8") as f:
        f.write("// Generated by build.py — do not edit by hand.\n")
        f.write("// Node ids equal their index in GRAPH.nodes.\n")
        f.write("const GRAPH = " + data + ";\n")
    if not quiet:
        groups = sorted({n["group"] for n in nodes})
        print(f"Indexed {len(nodes)} notes, {len(links)} links, groups: {', '.join(groups)}")
        print(f"Wrote {os.path.relpath(output, ROOT)}")
    return notes, nodes, links


if __name__ == "__main__":
    notes_dir = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_NOTES_DIR
    if not os.path.isdir(notes_dir):
        sys.exit(f"Notes folder not found: {notes_dir}")
    build(notes_dir)
