// Generated by build.py — do not edit by hand.
// Node ids equal their index in GRAPH.nodes.
const GRAPH = {
 "nodes": [
  {
   "id": 0,
   "label": "Cafe Luna Account",
   "group": "customers",
   "path": "customers/Cafe Luna Account.md",
   "excerpt": "Contact: Sofia Marquez (owner). Account since 2024.\n\n- Orders 25 lb/week of House Espresso Blend\n- We installed and service their grinder (loaned, ours)\n- Pays on time, net-15\n\n2026-09-10 call with Sofia:\n- She is opening a second location in the spring and may double the order to 50 lb/week\n- Wants a small discount at that volume — asked for $52/5 lb\n- Wants barista training for her new staff (we could adapt our Barista Training Program and charge for it)\n\nImplications: 50 lb/week more likely needs a Wednesday roast (see Roasting Schedule) and more green from Green Coffee Sourcing. Run the numbers in the Pricing Strategy before answering.",
   "degree": 7
  },
  {
   "id": 1,
   "label": "Catering Orders",
   "group": "customers",
   "path": "customers/Catering Orders.md",
   "excerpt": "We do coffee service for offices and events: 96 oz boxes of drip ($28), pastries from Rosie's, and a cold brew option in summer.\n\n2026 so far: 23 orders, $6,400 revenue. Biggest repeat client is Pier 9 Office (also one of our Wholesale Accounts).\n\nProcess\n1. Order via website form (Website Redesign should make this a proper page)\n2. 48 hours' notice — Rosie needs it per the Pastry Supplier Agreement\n3. Deposit 50% for orders over $200\n4. Delivery by Dev in the café car\n\nUpcoming: holiday party season. Promote in the November Email Newsletter; could be $3–4k in December alone.",
   "degree": 6
  },
  {
   "id": 2,
   "label": "Customer Feedback Summary Q3",
   "group": "customers",
   "path": "customers/Customer Feedback Summary Q3.md",
   "excerpt": "Sources: Google reviews (38 new, avg 4.7), comment cards (61), Instagram DMs.\n\nTop praise\n1. Friendly staff — Dev and Priya named by name repeatedly\n2. House Espresso Blend quality\n3. Pastries from Rosie's\n\nTop complaints\n1. Wait times on Saturday 9–11am (mentioned 17×) — see the Staff Roster weekend gap\n2. Not enough seating / laptop campers at peak\n3. Wants a digital Loyalty Program (11×)\n4. Oat milk upcharge ($0.75) feels unfair (9×) — discussed in Pricing Strategy\n5. Wants a darker roast option\n\nActions\n- Add a third barista Saturday mornings (Hiring Plan)\n- Test \"no laptops 9–12 weekends\" sign\n- Revisit oat upcharge in Q4 pricing",
   "degree": 5
  },
  {
   "id": 3,
   "label": "Loyalty Program",
   "group": "customers",
   "path": "customers/Loyalty Program.md",
   "excerpt": "Current: paper punch card, 10th drink free. No data, lots of lost cards.\n\nPlan: move to the POS loyalty module (Square) in November.\n- 1 point per $1, 100 points = free drink\n- Double points on the Seasonal Menu Autumn drinks in the first two weeks\n- Subscribers to the Subscription Box get 50 points a month\n\nCost estimate: ~2.5% of sales in redemptions based on the punch card redemption rate.\n\nThe Customer Feedback Summary Q3 mentions loyalty 11 times — people want it on their phone.\n\nPromote via Email Newsletter and at the Grand Reopening Event (sign-up table with a free cookie).",
   "degree": 9
  },
  {
   "id": 4,
   "label": "Wholesale Accounts",
   "group": "customers",
   "path": "customers/Wholesale Accounts.md",
   "excerpt": "Active accounts: 7. Wholesale is 18% of revenue, but 31% of roasted volume.\n\nAccount · Product · Volume/week\nCafe Luna · House Espresso Blend · 25 lb\nTidewater Books café · Harbor + decaf · 8 lb\nGreen Fork Deli · Drip blend · 10 lb\nPier 9 Office · Drip + cold brew · 6 lb\n3 small restaurants · Harbor · ~12 lb total\n\nTerms: net-15, delivered Monday. Orders in by Thursday noon for the Roasting Schedule.\n\nPrice: $58 per 5 lb bag of Harbor — below retail but still ~40% gross margin.\n\nBiggest account by far is the Cafe Luna Account. Concentration risk: if Luna leaves, wholesale drops by a third.",
   "degree": 6
  },
  {
   "id": 5,
   "label": "Cash Flow Forecast",
   "group": "finance",
   "path": "finance/Cash Flow Forecast.md",
   "excerpt": "Rolling 6 months, updated monthly. Cash on hand 2026-09-01: $23,400.\n\nKnown big outflows\n- October: pastry contract renewal (no cost), Grand Reopening Event (~$1,800)\n- November: forward contract deposit for green coffee (~$11,000) — see Green Coffee Sourcing\n- November: walk-in replacement if the Equipment Loan is approved (down payment $2,000)\n- December: annual insurance ($3,200)\n\nKnown inflows\n- Holiday retail bags and Catering Orders spike in December (+$9k vs. normal)\n- Subscription Box revenue ~$4,600/month, growing\n\nLow point: early December at roughly $8,500 if everything lands. Minimum comfort level is $10,000 — so either delay the forward contract or split it into two deposits.\n…",
   "degree": 6
  },
  {
   "id": 6,
   "label": "Equipment Loan",
   "group": "finance",
   "path": "finance/Equipment Loan.md",
   "excerpt": "Lender: Coastal Community Bank, small business equipment line.\n\nRequest: $14,000\n- Walk-in cooler replacement: $9,800 installed (after the compressor failure in the Equipment Maintenance Log)\n- Nitro cold brew keg system: $1,900 (Cold Brew Program)\n- Second grinder for decaf: $2,300\n\nTerms offered: 5 years, 8.4% fixed, ~$287/month. 15% down.\n\nPros: stops repeated repair costs, nitro adds a premium item.\nCons: adds a fixed payment while the Cash Flow Forecast shows a tight December.\n\nDecision: Maya meeting the bank 2026-10-06. Bring the Q3 Budget Review and two years of tax returns.",
   "degree": 5
  },
  {
   "id": 7,
   "label": "Pricing Strategy",
   "group": "finance",
   "path": "finance/Pricing Strategy.md",
   "excerpt": "Last price change: January 2025. Green coffee is up ~11% (see Green Coffee Sourcing) and labor is up; margins are squeezed.\n\nProposal for November 1\n- Drip: $3.25 → $3.50\n- Latte (12 oz): $5.25 → $5.50\n- Retail 12 oz bag: $17 → $18\n- Oat milk upcharge: $0.75 → $0.50 (complaint in Customer Feedback Summary Q3; cost difference is really ~$0.35)\n- Wholesale Harbor 5 lb: hold at $58; offer $54 at 40+ lb/week (answer for the Cafe Luna Account — not $52)\n\nExpected impact: +$2,800/month gross profit at current volume.\n\nCommunicate via the Email Newsletter a week before. Launch alongside the new Loyalty Program so it feels like a trade, not just an increase.",
   "degree": 8
  },
  {
   "id": 8,
   "label": "Q3 Budget Review",
   "group": "finance",
   "path": "finance/Q3 Budget Review.md",
   "excerpt": "Period: July–September 2026 (September estimated).\n\n · Budget · Actual · Variance\nRevenue · $118,000 · $124,600 · +5.6%\nCost of goods · $38,900 · $42,300 · −8.7%\nLabor · $41,000 · $43,800 · −6.8%\nRent & utilities · $12,600 · $12,900 · −2.4%\nMarketing · $3,000 · $2,150 · +28%\n\nTakeaways\n- Revenue beat budget thanks to cold brew and the Subscription Box\n- COGS over budget: green coffee price increases and pastry waste\n- Labor over: overtime covering Saturday shifts (see Staff Roster)\n- Walk-in fridge repair was unplanned ($610, Equipment Maintenance Log)\n\nActions for Q4: price changes in the Pricing Strategy, hire per the Hiring Plan, and update the Cash Flow Forecast.",
   "degree": 9
  },
  {
   "id": 9,
   "label": "Supplier Invoices",
   "group": "finance",
   "path": "finance/Supplier Invoices.md",
   "excerpt": "Process: every invoice is matched to a delivery and to the Sunday count from the Inventory Process before payment. Paid Thursdays.\n\nSupplier · Terms · Avg monthly\nNorthbound Green Co. · net-30 · $5,900\nHillside Dairy · net-15 · $3,100\nRosie's Bakehouse · weekly · $4,700\nRestaurant Depot · card · $1,300\nSquare (POS) · auto · $1,650\n\nProblem in August: Hillside Dairy billed for 12 gallons we never received — caught because of the count match. Credit issued.\n\nRosie's invoices will change if the new minimums in the Pastry Supplier Agreement go through.",
   "degree": 2
  },
  {
   "id": 10,
   "label": "Email Newsletter",
   "group": "marketing",
   "path": "marketing/Email Newsletter.md",
   "excerpt": "Platform: Mailchimp. 2,140 subscribers, 41% open rate, 3.8% click rate.\n\nMonthly issue (first Tuesday) template\n1. What's roasting — featured single origin\n2. Seasonal drink spotlight\n3. Subscription Box reminder / gift idea\n4. Community — Local Partnerships, events\n\nUpcoming\n- Oct 7: Grand Reopening Event announcement + Seasonal Menu Autumn\n- Oct 16: reopening reminder\n- Late Oct: price change notice (Pricing Strategy) framed with the new Loyalty Program\n- Nov: holiday Catering Orders and gift subscriptions\n\nList growth: add sign-up to the Website Redesign and at the reopening.",
   "degree": 8
  },
  {
   "id": 11,
   "label": "Grand Reopening Event",
   "group": "marketing",
   "path": "marketing/Grand Reopening Event.md",
   "excerpt": "Date: Saturday 2026-10-18, 8am–2pm. Celebrating the refreshed seating area (18 → 26 seats) and the Seasonal Menu Autumn.\n\nPlan\n- $2 drip all day, free cookie with Loyalty Program sign-up\n- Latte art throwdown at 11am (Priya hosting)\n- Live acoustic set 12–1 (Tidewater Books is lending the PA — Local Partnerships)\n- Cold brew samples from the Cold Brew Program\n\nStaffing: all hands, 5 on bar. See Staff Roster.\n\nBudget ~$1,800 (in the Cash Flow Forecast): signage $300, cookies $400, musician $250, extra labor $850.\n\nPromotion: Instagram Content Plan countdown, Email Newsletter on Oct 7 and Oct 16, flyers at the farmers market.\n\nSuccess = 400+ transactions (normal Saturday ~260) and 150 loyalty…",
   "degree": 10
  },
  {
   "id": 12,
   "label": "Instagram Content Plan",
   "group": "marketing",
   "path": "marketing/Instagram Content Plan.md",
   "excerpt": "Account: @harborstreetcoffee — 4,870 followers, ~3.2% engagement.\n\nWeekly cadence\n- Monday: roast day behind-the-scenes (Roasting Schedule)\n- Wednesday: drink feature (Seasonal Menu Autumn in Sept–Nov)\n- Friday: staff spotlight (rotate through the Staff Roster, with consent)\n- Stories daily: pastry case at open\n\nOctober focus: countdown to the Grand Reopening Event — 3 teaser reels showing the new seating layout.\n\nReels outperform photos 3:1. Best time to post: 7:30am and 12:30pm.\n\nBudget: $150/month boosted posts, geo-targeted 5 miles. Tie-ins with Local Partnerships (tag the bookstore and the farmers market).",
   "degree": 6
  },
  {
   "id": 13,
   "label": "Local Partnerships",
   "group": "marketing",
   "path": "marketing/Local Partnerships.md",
   "excerpt": "Tidewater Books\n- Also one of our Wholesale Accounts\n- Joint \"book + coffee\" gift card for the holidays\n- Lending the PA for the Grand Reopening Event\n\nHarbor Farmers Market (Saturdays, May–Oct)\n- Our booth sells retail bags and cold brew growlers — ~$900/Saturday in summer\n- Last market of the year Oct 25\n\nSeaside High School\n- Donate day-old pastries to the after-school program (reduces waste in the Inventory Process log and it's good will)\n- Possible part-time hires from their culinary program — see Hiring Plan\n\nIdeas: running club meets at the café Sunday 7am; offer 10% off post-run.",
   "degree": 6
  },
  {
   "id": 14,
   "label": "Website Redesign",
   "group": "marketing",
   "path": "marketing/Website Redesign.md",
   "excerpt": "Current site: Squarespace template from 2022. Slow on mobile, no catering page, subscriptions handled through a clunky plugin.\n\nGoals\n1. Subscription Box management with pause/skip (retention!)\n2. Proper Catering Orders page with a quote form\n3. Wholesale inquiry page (Wholesale Accounts are all word-of-mouth right now)\n4. Retail bag shop with local pickup\n5. Newsletter sign-up tied to the Email Newsletter list\n\nOptions\n- Stay on Squarespace + ReCharge for subscriptions (~$1,200 setup)\n- Move to Shopify ($2,500–4,000 with a freelancer)\n\nFreelancer quote from Jonah Park: $3,200, 6 weeks. Would like it live before the holiday season, which means deciding by mid-October.",
   "degree": 4
  },
  {
   "id": 15,
   "label": "Equipment Maintenance Log",
   "group": "operations",
   "path": "operations/Equipment Maintenance Log.md",
   "excerpt": "Date · Equipment · Issue / Work · Cost\n2026-06-14 · Diedrich roaster · Chaff collector cleaned, exhaust fan bearing replaced · $340\n2026-07-02 · La Marzocco Linea (café) · Group gaskets + shower screens · $120\n2026-08-19 · Mazzer grinder #2 · Burrs replaced after ~900 kg · $260\n2026-09-03 · Walk-in fridge · Compressor fault — service call, milk loss ~$180 · $610\n\nNotes:\n- Roaster afterburner is due for inspection in November; the fire marshal wants the certificate in the Health Inspection Checklist binder.\n- The walk-in failure is why we are looking at the Equipment Loan for a replacement unit rather than patching it again.\n- Descale espresso machine monthly; Priya owns this on the Staff…",
   "degree": 5
  },
  {
   "id": 16,
   "label": "Green Coffee Sourcing",
   "group": "operations",
   "path": "operations/Green Coffee Sourcing.md",
   "excerpt": "Importer: Northbound Green Co. (rep: Luis). Minimum order 10 bags (69 kg each), net-30 terms.\n\nCurrent lots:\n- Colombia Huila, washed — base of the House Espresso Blend, $4.85/lb\n- Brazil Cerrado, natural — body for espresso, $3.90/lb\n- Ethiopia Guji, natural — seasonal single origin, $6.20/lb\n- Peru Cajamarca SWP decaf — $5.40/lb\n\nGreen prices are up about 11% year over year. That is the main driver behind the changes in the Pricing Strategy note.\n\nWe store green in the back room on pallets, off the floor, below 24°C. Humidity logger checks happen during the weekly Inventory Process.\n\nPlan: sign a forward contract for 30 bags of Huila before December to lock the price. Needs sign-off…",
   "degree": 7
  },
  {
   "id": 17,
   "label": "Health Inspection Checklist",
   "group": "operations",
   "path": "operations/Health Inspection Checklist.md",
   "excerpt": "Last inspection: 2026-05-22, score 96/100. Next expected: November.\n\nDeductions last time: one unlabeled container of oat milk, hand sink blocked by a mop bucket.\n\nDaily\n- Fridge temps logged at open and close (≤ 4°C). See Opening and Closing Procedures.\n- Sanitizer buckets at 200 ppm quat, changed every 4 hours\n- Date labels on all milk, pastries, and cold brew concentrate\n\nWeekly\n- Deep clean under the bar and behind the grinders\n- Pest control log checked (Orkin visits monthly)\n\nDocuments in the binder: food handler cards for every barista (tracked in Barista Training Program), roaster afterburner certificate, the pastry supplier's license from the Pastry Supplier Agreement.",
   "degree": 6
  },
  {
   "id": 18,
   "label": "Inventory Process",
   "group": "operations",
   "path": "operations/Inventory Process.md",
   "excerpt": "Every Sunday at close, Dev counts:\n- Milk (dairy, oat, almond) and cream\n- Cups, lids, sleeves, cold cups\n- Retail bags and labels\n- Green coffee by lot (with humidity reading)\n- Syrups and seasonal ingredients for the Seasonal Menu Autumn\n\nCounts go in the shared sheet. Par levels: 40 gal dairy, 18 cases oat, 2,000 hot cups.\n\nOrders go out Monday morning. Paper goods via Restaurant Depot; milk via Hillside Dairy (Tue/Fri drops).\n\nWaste is logged separately — it has been running around 6% of food cost, target is under 4%. Most of it is day-old pastry; we are renegotiating quantities in the Pastry Supplier Agreement.\n\nSupplier Invoices get matched against Sunday counts before anything is…",
   "degree": 8
  },
  {
   "id": 19,
   "label": "Opening and Closing Procedures",
   "group": "operations",
   "path": "operations/Opening and Closing Procedures.md",
   "excerpt": "Opening (6:15 for 7:00 doors)\n1. Turn on espresso machine and grinders; flush groups\n2. Dial in the House Espresso Blend — 18 g in, 38 g out, 27–30 s\n3. Log fridge temps (Health Inspection Checklist)\n4. Receive pastry delivery and check against the order\n5. Brew first batch of drip; set up cold brew station per the Cold Brew Program\n\nClosing (5:00 doors, out by 5:45)\n1. Backflush machine, soak portafilters\n2. Clean grinders, empty hoppers into airtight bins\n3. Log fridge temps, label anything opened\n4. Count the till; drop goes in the safe\n5. Sundays only: run the Inventory Process\n\nNew hires shadow two opens and two closes before working solo — part of the Barista Training Program.",
   "degree": 5
  },
  {
   "id": 20,
   "label": "Roasting Schedule",
   "group": "operations",
   "path": "operations/Roasting Schedule.md",
   "excerpt": "Updated: 2026-09-08 · Owner: Maya\n\nWe roast on the 12 kg Diedrich every Tuesday and Friday, 6:00–11:00, before the café gets busy enough to need Dev on the floor.\n\n- Tuesday: House Espresso Blend (4 batches), single origins for retail bags (2–3 batches)\n- Friday: House Espresso Blend (3 batches), decaf, and whatever the Subscription Box needs that week\n- Wholesale Accounts are roasted to order on Friday and delivered Monday, so orders must be in by Thursday noon.\n\nRest times: espresso needs at least 5 days before it hits the grinder; filter is fine at 3.\n\nGreen stock comes from Green Coffee Sourcing. If a batch drops more than 2% below target weight loss, log it in the Equipment Maintenance…",
   "degree": 8
  },
  {
   "id": 21,
   "label": "Cold Brew Program",
   "group": "products",
   "path": "products/Cold Brew Program.md",
   "excerpt": "Batch: 5 lb coarse ground Brazil Cerrado + 5 gal filtered water, 18-hour steep in the Toddy, filtered twice. Yields ~3.5 gal concentrate. Dilute 1:1 for service.\n\nShelf life: 7 days refrigerated, labeled with brew date (Health Inspection Checklist requirement).\n\nSales: cold brew was 22% of summer drink sales. Drops to ~8% in winter.\n\nRetail: 32 oz growlers of concentrate ($16) sell well at the farmers market and are an add-on in the Subscription Box.\n\nNext: nitro tap. Needs a keg system (~$1,900); pencil it into the Equipment Loan scope if the bank allows. The Spiced Pear Cold Brew on the Seasonal Menu Autumn uses this concentrate.",
   "degree": 6
  },
  {
   "id": 22,
   "label": "House Espresso Blend",
   "group": "products",
   "path": "products/House Espresso Blend.md",
   "excerpt": "House Espresso Blend — \"Harbor\"\n60% Colombia Huila washed / 40% Brazil Cerrado natural. Roasted to a medium, ~14.5% weight loss, dropped at 214°C.\n\nTasting notes on the bag: milk chocolate, toasted almond, cherry.\n\nThis is 70% of our roasted volume: all café espresso drinks, most Wholesale Accounts, and the \"classic\" option in the Subscription Box.\n\nRecipe card: 18 g in, 38 g out, 27–30 s, 93°C.\n\nCost per lb roasted (green + loss + labor + bag): about $8.10. Retail 12 oz bag sells for $17, wholesale 5 lb is $58 — see Pricing Strategy.\n\nCustomers in the Customer Feedback Summary Q3 asked for a darker option. Trial batch planned for October; if it works it becomes a second blend rather than…",
   "degree": 10
  },
  {
   "id": 23,
   "label": "Pastry Supplier Agreement",
   "group": "products",
   "path": "products/Pastry Supplier Agreement.md",
   "excerpt": "Supplier: Rosie's Bakehouse (owner: Rosie Alvarez). Signed 2025-11-01, 12-month term, auto-renews unless either side gives 30 days' notice.\n\nTerms\n- Daily delivery by 6:30, Tuesday–Sunday\n- Consignment is NOT allowed — we buy outright at 55% of retail\n- Minimum 36 items/day\n- Rosie supplies her cottage food / commercial kitchen license copy for our Health Inspection Checklist binder\n\nIssues\n- Waste on day-old pastry is the biggest line in the Inventory Process waste log\n- Proposal to Rosie: drop minimum to 28 items on Tue/Wed, keep 36 on weekends\n- Catering Orders need 48 hours' notice to Rosie\n\nRenewal decision due 2026-10-01. Leaning renew with revised minimums.",
   "degree": 6
  },
  {
   "id": 24,
   "label": "Seasonal Menu Autumn",
   "group": "products",
   "path": "products/Seasonal Menu Autumn.md",
   "excerpt": "Launch date: 2026-09-22. Runs through November.\n\nDrinks\n- Maple Cardamom Latte — house maple syrup, cardamom, oat milk default ($6.25)\n- Spiced Pear Cold Brew — built on the Cold Brew Program concentrate ($5.75)\n- Ethiopia Guji pour-over feature ($5.50)\n\nFood\n- Pumpkin-pecan scone and apple hand pie from Rosie's Bakehouse (see Pastry Supplier Agreement)\n\nMarketing: launch photos and reels are in the Instagram Content Plan; the menu also headlines the Grand Reopening Event on October 18.\n\nStaff need a 30-minute tasting and recipe walkthrough — scheduled in the Team Meeting Notes September.\n\nTarget: seasonal drinks at 20% of drink sales. Summer menu hit 14%.",
   "degree": 9
  },
  {
   "id": 25,
   "label": "Subscription Box",
   "group": "products",
   "path": "products/Subscription Box.md",
   "excerpt": "Launched March 2026. Customers choose:\n- Classic: 2 × 12 oz House Espresso Blend ($30/month)\n- Explorer: 2 × single origin, rotating ($36/month)\n- Add-on: cold brew concentrate growler (+$14)\n\nSubscribers: 142 as of September (up from 97 in June). Churn ~6%/month, mostly after month 3.\n\nFulfillment: roasted Friday per the Roasting Schedule, packed Saturday, shipped Monday via USPS. Shipping is our biggest margin leak — $7.80 average.\n\nRetention ideas:\n- Handwritten note + a sample of next month's coffee\n- Loyalty Program points for subscribers\n- Pause option instead of cancel (Website Redesign needs to support this)\n\nMentioned monthly in the Email Newsletter.",
   "degree": 8
  },
  {
   "id": 26,
   "label": "Barista Training Program",
   "group": "team",
   "path": "team/Barista Training Program.md",
   "excerpt": "Owner: Priya. Length: 3 weeks for a new hire.\n\nWeek 1 — Foundations\n- Food handler card (required, for the Health Inspection Checklist)\n- Opening and Closing Procedures: shadow 2 opens, 2 closes\n- Drip, cold brew, register\n\nWeek 2 — Espresso\n- Dialing in the House Espresso Blend\n- Milk steaming and latte art basics\n- Workflow on a busy bar\n\nWeek 3 — Service\n- Seasonal Menu Autumn drinks\n- Handling complaints, Loyalty Program sign-ups\n- Solo shifts with a lead on the floor\n\nSign-off: Priya checks 10 drinks in a row to spec.\n\nOpportunity: package a 2-day version for wholesale partners — the Cafe Luna Account asked for it. Price idea: $400 per trainee.",
   "degree": 8
  },
  {
   "id": 27,
   "label": "Hiring Plan",
   "group": "team",
   "path": "team/Hiring Plan.md",
   "excerpt": "Q4 2026\n\n1. Part-time weekend barista (Sat/Sun, ~16 hrs) — start by mid-October, before the Grand Reopening Event if possible\n   - Posting on Indeed + the Seaside High culinary program via Local Partnerships\n   - $17/hr + tips (~$6/hr average)\n2. Seasonal holiday helper, December only, for retail bags and Catering Orders\n\nNot hiring (yet): a production roaster assistant. Revisit if the Cafe Luna Account doubles and we add a Wednesday roast.\n\nCost: ~$1,500/month for the weekend role — covered if it cuts the Saturday overtime flagged in the Q3 Budget Review.\n\nOnboarding follows the Barista Training Program. Update the Staff Roster once hired.",
   "degree": 9
  },
  {
   "id": 28,
   "label": "Staff Roster",
   "group": "team",
   "path": "team/Staff Roster.md",
   "excerpt": "As of September 2026.\n\nName · Role · Hours/week · Notes\nMaya Chen · Owner, roaster · 50+ · Roasting Schedule, finance\nDev Patel · Café manager · 40 · Inventory Process, catering delivery\nPriya Nair · Lead barista · 36 · Machine descaling, trainer\nSam Okafor · Barista · 28 ·\nLena Brooks · Barista · 20 · Weekends\nTheo Ruiz · Barista · 16 · Student, weekends only\n\nGap: Saturday 8am–12pm has only 2 on bar; that is the wait-time complaint in the Customer Feedback Summary Q3. Overtime to cover it pushed labor over in the Q3 Budget Review.\n\nFix: see Hiring Plan — one part-time weekend barista.",
   "degree": 8
  },
  {
   "id": 29,
   "label": "Team Meeting Notes September",
   "group": "team",
   "path": "team/Team Meeting Notes September.md",
   "excerpt": "Date: 2026-09-15. Present: Maya, Dev, Priya, Sam, Lena.\n\n1. Seasonal Menu Autumn launches the 22nd — tasting on the 20th after close, everyone paid for the hour\n2. Grand Reopening Event roles: Priya runs the throwdown, Dev runs the sign-up table, Sam and Lena on bar\n3. Saturday rush: team agrees a third person 8–12 is the fix; Theo can do two Saturdays until the Hiring Plan role is filled\n4. Oat milk upcharge — staff get asked about it daily; Maya says it's going down in the Pricing Strategy change\n5. Walk-in fridge: temporary fix holding, replacement depends on the Equipment Loan\n\nAction items\n- Dev: finish Loyalty Program setup in Square by Nov 1\n- Priya: update Barista Training Program…",
   "degree": 8
  }
 ],
 "links": [
  {
   "source": 0,
   "target": 4,
   "kind": "mention"
  },
  {
   "source": 0,
   "target": 7,
   "kind": "mention"
  },
  {
   "source": 0,
   "target": 16,
   "kind": "mention"
  },
  {
   "source": 0,
   "target": 20,
   "kind": "mention"
  },
  {
   "source": 0,
   "target": 22,
   "kind": "mention"
  },
  {
   "source": 0,
   "target": 26,
   "kind": "mention"
  },
  {
   "source": 0,
   "target": 27,
   "kind": "mention"
  },
  {
   "source": 1,
   "target": 4,
   "kind": "mention"
  },
  {
   "source": 1,
   "target": 5,
   "kind": "mention"
  },
  {
   "source": 1,
   "target": 10,
   "kind": "mention"
  },
  {
   "source": 1,
   "target": 14,
   "kind": "mention"
  },
  {
   "source": 1,
   "target": 23,
   "kind": "mention"
  },
  {
   "source": 1,
   "target": 27,
   "kind": "mention"
  },
  {
   "source": 2,
   "target": 3,
   "kind": "mention"
  },
  {
   "source": 2,
   "target": 7,
   "kind": "mention"
  },
  {
   "source": 2,
   "target": 22,
   "kind": "mention"
  },
  {
   "source": 2,
   "target": 27,
   "kind": "mention"
  },
  {
   "source": 2,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 3,
   "target": 7,
   "kind": "mention"
  },
  {
   "source": 3,
   "target": 10,
   "kind": "mention"
  },
  {
   "source": 3,
   "target": 11,
   "kind": "mention"
  },
  {
   "source": 3,
   "target": 12,
   "kind": "shared"
  },
  {
   "source": 3,
   "target": 24,
   "kind": "mention"
  },
  {
   "source": 3,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 3,
   "target": 26,
   "kind": "mention"
  },
  {
   "source": 3,
   "target": 29,
   "kind": "mention"
  },
  {
   "source": 4,
   "target": 13,
   "kind": "mention"
  },
  {
   "source": 4,
   "target": 14,
   "kind": "mention"
  },
  {
   "source": 4,
   "target": 20,
   "kind": "mention"
  },
  {
   "source": 4,
   "target": 22,
   "kind": "mention"
  },
  {
   "source": 5,
   "target": 6,
   "kind": "mention"
  },
  {
   "source": 5,
   "target": 8,
   "kind": "mention"
  },
  {
   "source": 5,
   "target": 11,
   "kind": "mention"
  },
  {
   "source": 5,
   "target": 16,
   "kind": "mention"
  },
  {
   "source": 5,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 6,
   "target": 8,
   "kind": "mention"
  },
  {
   "source": 6,
   "target": 15,
   "kind": "mention"
  },
  {
   "source": 6,
   "target": 21,
   "kind": "mention"
  },
  {
   "source": 6,
   "target": 29,
   "kind": "mention"
  },
  {
   "source": 7,
   "target": 8,
   "kind": "mention"
  },
  {
   "source": 7,
   "target": 10,
   "kind": "mention"
  },
  {
   "source": 7,
   "target": 16,
   "kind": "mention"
  },
  {
   "source": 7,
   "target": 22,
   "kind": "mention"
  },
  {
   "source": 7,
   "target": 29,
   "kind": "mention"
  },
  {
   "source": 8,
   "target": 15,
   "kind": "mention"
  },
  {
   "source": 8,
   "target": 16,
   "kind": "shared"
  },
  {
   "source": 8,
   "target": 22,
   "kind": "shared"
  },
  {
   "source": 8,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 8,
   "target": 27,
   "kind": "mention"
  },
  {
   "source": 8,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 9,
   "target": 18,
   "kind": "mention"
  },
  {
   "source": 9,
   "target": 23,
   "kind": "mention"
  },
  {
   "source": 10,
   "target": 11,
   "kind": "mention"
  },
  {
   "source": 10,
   "target": 13,
   "kind": "mention"
  },
  {
   "source": 10,
   "target": 14,
   "kind": "mention"
  },
  {
   "source": 10,
   "target": 24,
   "kind": "mention"
  },
  {
   "source": 10,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 11,
   "target": 12,
   "kind": "mention"
  },
  {
   "source": 11,
   "target": 13,
   "kind": "mention"
  },
  {
   "source": 11,
   "target": 21,
   "kind": "mention"
  },
  {
   "source": 11,
   "target": 24,
   "kind": "mention"
  },
  {
   "source": 11,
   "target": 27,
   "kind": "mention"
  },
  {
   "source": 11,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 11,
   "target": 29,
   "kind": "mention"
  },
  {
   "source": 12,
   "target": 13,
   "kind": "mention"
  },
  {
   "source": 12,
   "target": 20,
   "kind": "mention"
  },
  {
   "source": 12,
   "target": 24,
   "kind": "mention"
  },
  {
   "source": 12,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 13,
   "target": 18,
   "kind": "mention"
  },
  {
   "source": 13,
   "target": 27,
   "kind": "mention"
  },
  {
   "source": 14,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 15,
   "target": 17,
   "kind": "mention"
  },
  {
   "source": 15,
   "target": 20,
   "kind": "mention"
  },
  {
   "source": 15,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 16,
   "target": 18,
   "kind": "mention"
  },
  {
   "source": 16,
   "target": 20,
   "kind": "mention"
  },
  {
   "source": 16,
   "target": 22,
   "kind": "mention+shared"
  },
  {
   "source": 17,
   "target": 18,
   "kind": "shared"
  },
  {
   "source": 17,
   "target": 19,
   "kind": "mention"
  },
  {
   "source": 17,
   "target": 21,
   "kind": "mention"
  },
  {
   "source": 17,
   "target": 23,
   "kind": "mention"
  },
  {
   "source": 17,
   "target": 26,
   "kind": "mention"
  },
  {
   "source": 18,
   "target": 19,
   "kind": "mention"
  },
  {
   "source": 18,
   "target": 23,
   "kind": "mention"
  },
  {
   "source": 18,
   "target": 24,
   "kind": "mention"
  },
  {
   "source": 18,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 19,
   "target": 21,
   "kind": "mention"
  },
  {
   "source": 19,
   "target": 22,
   "kind": "mention"
  },
  {
   "source": 19,
   "target": 26,
   "kind": "mention"
  },
  {
   "source": 20,
   "target": 22,
   "kind": "mention"
  },
  {
   "source": 20,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 20,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 21,
   "target": 24,
   "kind": "mention"
  },
  {
   "source": 21,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 22,
   "target": 25,
   "kind": "mention"
  },
  {
   "source": 22,
   "target": 26,
   "kind": "mention"
  },
  {
   "source": 23,
   "target": 24,
   "kind": "mention"
  },
  {
   "source": 23,
   "target": 29,
   "kind": "mention"
  },
  {
   "source": 24,
   "target": 26,
   "kind": "mention"
  },
  {
   "source": 24,
   "target": 29,
   "kind": "mention"
  },
  {
   "source": 26,
   "target": 27,
   "kind": "mention"
  },
  {
   "source": 26,
   "target": 29,
   "kind": "mention"
  },
  {
   "source": 27,
   "target": 28,
   "kind": "mention"
  },
  {
   "source": 27,
   "target": 29,
   "kind": "mention"
  }
 ]
};
